language: go

go:
  - 1.x

env:
  - GO111MODULE=on

services:
  - docker

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

before_script:
  - docker pull oszura/smarthome-server-test
  - docker run -d -p 127.0.0.1:3222:3222 oszura/smarthome-server-test /bin/sh
  - make lint
  - make test
  - sleep 60
  - docker ps -a
  - make integration-test
