language: go

go:
  - 1.x

env:
  - GO111MODULE=on

install:
  - sudo apt install libgconf-2-4
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

before_script:
  - make lint
  - make test
  - make integration-test
