language: go

go:
  - 1.x

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install
  - make install

before_script:
  - make lint
  - make test

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
  - env GO111MODULE=on go vet
