language: go

go:
  - 1.x

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - docker pull oszura/smarthome-server-test

install:
  - make install

script:
  - docker run -it -d --name build -p 127.0.0.1:3222:3222 -v $PWD:/root/go/src/github.com/smart-evolution/smarthome oszura/smarthome-server-test /bin/bash
  - sleep 30
  - make integration-test

