apiVersion: v1
kind: Service
metadata:
  name: sh-api
spec:
  externalIPs:
    - 192.168.2.117
  ports:
    - port: 3222
      protocol: TCP
      targetPort: 3222
      nodePort: 30222
  selector:
    app: sh-api
  type: NodePort

